version: "3.8"
services:
  sy6:
    container_name: "${PROJECT_NAME}" # Nombre del contenedor
    build: # Construción de la imagen custom de php 8.1 desde el archivo Dockerfile en la raiz de este direcortio php8.1
      context: .
      dockerfile: ./Dockerfile
      labels:
        - com.host.description=${PROJECT_NAME}
      args: # Argumentos de la imagen
        PROJECT_SY_NAME: ${PROJECT_SY_NAME}
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    volumes:
      - ./config/local.ini:/usr/local/etc/php/conf.d/local.ini # Se habilita la configuración del local
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf # Archivo de configuración del apache de la ruta del servidor
      # Estas líneas son cuando no se usa traefik y el propio apache genera el ssl
      # - ./config/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf # Archivo de configuración del apache de la ruta del servidor
      # - ./ssl/:/etc/apache2/ssl # Se crea el volumen de los certificados seguros para cambiarlos cuando se caducan
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # Configuración de xdebug para php
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini #Configuración de Xdebug para docker
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini # Se habilita los errores
      #- ./config/.bashrc:/root/.bashrc # Se habilita el bashrc para el root
      - $PATH_BASE/phpProjects/${PROJECT_SY_NAME}:/var/www/html/ # Copiamos la ruta del proyecto
    labels:
      - traefik.enable=true
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${SYMFONY_URL}.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
    networks:
      server_proxy:
# Red Puente
networks:
  server_proxy:
    name: server_proxy
    driver: bridge
